# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-NoFollow
version:      1.000
version_from: lib/Template/Plugin/NoFollow.pm
installdirs:  site
requires:
    Template:                      2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
