---
name: Template-Plugin-NoFollow
version: 1.02
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: TT filter to add rel="nofollow" to all HTML links
license: perl
resources:
  license: ~
requires:
  HTML::Parser: 0
  Template: 2
build_requires:
  Test::More: 0
provides:
  Template::Plugin::NoFollow:
    file: lib/Template/Plugin/NoFollow.pm
    version: 1.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
